CREATE TABLE PERFIS (
	ID INT NOT NULL, 
	PERFIL VARCHAR (20) NOT NULL, 
	PRIMARY KEY (ID)
);
/
INSERT INTO PERFIS (ID, PERFIL) 
	VALUES (1, 'CLIENTE'), 
	(2, 'VETERINARIO'), 
	(3, 'ATENDENTE'), 
	(4, 'ADMINISTRADOR');
/
CREATE TABLE PESSOA (ID INT NOT NULL, 
	ID_PERFIL INT NOT NULL, 
	ID_ENDERECO INT NOT NULL,
	NOME VARCHAR(100) NOT NULL, 
	CPF VARCHAR(100) NOT NULL,
	IDENTIDADE VARCHAR(100) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_PERFIL) REFERENCES PERFIS (ID), 
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)	
);
/
INSERT INTO PESSOA (ID, ID_PERFIL, ID_ENDERECO, NOME, CPF, IDENTIDADE, EMAIL, SENHA)
	VALUES (1, 1, 1, 'SANDRO', '8844', 'MG20', 'sandro@mail.com', '12345'), 
	(2, 2, 1, 'OLIVEIRA', '2554', 'SP40', 'oliveira@mail.com', '12345'), 
	(3, 3, 1, 'BRAGA', '5511', 'PR20', 'braga@mail.com', '12345'),
	(4, 4, 1, 'BORGES', '2254', 'BA54', 'borges@mail.com', '12345');

/
CREATE TABLE VETERINARIO(
	ID INT NOT NULL, CRV VARCHAR(50) NOT NULL, 
	ID_TIPO_ANIMAL INT NOT NULL,
	FOREIGN KEY (ID) REFERENCES PESSOA (ID),
	FOREIGN KEY (ID_TIPO_ANIMAL) REFERENCES TIPO_ANIMAL(ID)
);
/
CREATE TABLE ADMINISTRADOR(ID INT NOT NULL, 
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);
/
CREATE TABLE ATENDENTE(ID INT NOT NULL, 
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);
/
CREATE TABLE TIPO_ANIMAL(ID INT NOT NULL, 
	TIPO VARCHAR(30) NOT NULL, 
	PRIMARY KEY (ID)
);
/
CREATE TABLE ENDERECO (ID INT NOT NULL, 
	RUA VARCHAR(100) NOT NULL, 
	NUMERO INT NOT NULL,
	CEP VARCHAR(100) NOT NULL, 
	BAIRRO VARCHAR(100) NOT NULL,
	UF VARCHAR(2) NOT NULL, 
	CIDADE VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);
/
INSERT INTO ENDERECO (ID, RUA, NUMERO, CEP, BAIRRO, UF, CIDADE)
	VALUES(1, 'COROMANDEL', 10, '38785000', 'CENTRO', 'MG', 'UBERLANDIA');
/
CREATE TABLE SERVICO(ID INT NOT NULL, 
	TEMPO DATE NOT NULL, VALOR_PATAZ DECIMAL(10,2),
	CASHBACK_PATAZ DECIMAL(10,2), 
	VALOR_REAL DECIMAL(10,2) NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);



